#!/usr/bin/env bash
# Eemalda 60+ päeva inaktiivsed DHCP reservation-id.
#
# Paigaldatakse: /usr/local/sbin/dhcp-reservation-cleanup.sh
# Käivitatakse: kord päevas systemd timer-iga (dhcp-reservation-cleanup.timer)
set -euo pipefail
PATH=/usr/sbin:/usr/bin:/sbin:/bin

STATE_DIR=/var/lib/kohvrikapid-agent
RESERV_FILE="$STATE_DIR/dhcp-reservations.tsv"
DNSMASQ_RESERV=/etc/dnsmasq.d/kohvrikapid-reservations.conf
EXPIRE_DAYS=60

[ -f "$RESERV_FILE" ] || exit 0

NOW="$(date +%s)"
CUTOFF=$(( NOW - EXPIRE_DAYS * 86400 ))
TMP="$(mktemp)"
REMOVED=0

while IFS=$'\t' read -r mac ip ts host; do
  if [ -z "$mac" ] || [ -z "$ts" ]; then continue; fi
  if [ "$ts" -lt "$CUTOFF" ] 2>/dev/null; then
    REMOVED=$((REMOVED+1))
    logger -t dhcp-reserv "EXPIRE $mac ($ip) — last seen $(date -d @$ts -Iseconds 2>/dev/null || echo $ts)"
    continue
  fi
  printf "%s\t%s\t%s\t%s\n" "$mac" "$ip" "$ts" "$host" >> "$TMP"
done < "$RESERV_FILE"

mv "$TMP" "$RESERV_FILE"

# Värskenda dnsmasq config-i
{
  echo "# Auto-generated by dhcp-reservation-cleanup — $(date -Iseconds)"
  while IFS=$'\t' read -r m i t h; do
    [ -n "$m" ] && [ -n "$i" ] && echo "dhcp-host=$m,$i"
  done < "$RESERV_FILE"
} > "$DNSMASQ_RESERV.tmp"
mv "$DNSMASQ_RESERV.tmp" "$DNSMASQ_RESERV"

if [ "$REMOVED" -gt 0 ]; then
  systemctl reload dnsmasq 2>/dev/null || pkill -HUP -x dnsmasq || true
  logger -t dhcp-reserv "cleanup removed $REMOVED expired reservations"
fi
