#!/usr/bin/env bash
# dnsmasq dhcp-script hook: tagasta IP samale MAC-ile alati.
#
# dnsmasq kutsub: $1=action (add/old/del) $2=mac $3=ip $4=hostname
# Salvestame /var/lib/kohvrikapid-agent/dhcp-reservations.tsv-i: MAC<TAB>IP<TAB>LAST_SEEN_EPOCH
# Eraldi cron (dhcp-reservation-cleanup.sh) eemaldab 60+ päeva inaktiivsed
# kirjed ja sünkroniseerib /etc/dnsmasq.d/kohvrikapid-reservations.conf-i.
#
# Paigaldatakse: /usr/local/sbin/dhcp-reservation-hook.sh
set -euo pipefail
PATH=/usr/sbin:/usr/bin:/sbin:/bin

ACTION="${1:-}"
MAC="${2:-}"
IP="${3:-}"
HOST="${4:-}"

STATE_DIR=/var/lib/kohvrikapid-agent
RESERV_FILE="$STATE_DIR/dhcp-reservations.tsv"
DNSMASQ_RESERV=/etc/dnsmasq.d/kohvrikapid-reservations.conf

mkdir -p "$STATE_DIR"
touch "$RESERV_FILE"

# Salvesta kõigil add/old action-itel (DHCPACK)
case "$ACTION" in
  add|old)
    if [ -n "$MAC" ] && [ -n "$IP" ]; then
      MAC_LC="$(echo "$MAC" | tr '[:upper:]' '[:lower:]')"
      NOW="$(date +%s)"
      # Eemalda vana rida, lisa uus
      TMP="$(mktemp)"
      grep -v "^$MAC_LC	" "$RESERV_FILE" > "$TMP" || true
      printf "%s\t%s\t%s\t%s\n" "$MAC_LC" "$IP" "$NOW" "$HOST" >> "$TMP"
      mv "$TMP" "$RESERV_FILE"
      logger -t dhcp-reserv "ACK $MAC_LC → $IP ($HOST)"

      # Värskenda dnsmasq reservation faili (dhcp-host=MAC,IP rida)
      {
        echo "# Auto-generated by dhcp-reservation-hook — last update $(date -Iseconds)"
        while IFS=$'\t' read -r m i t h; do
          [ -n "$m" ] && [ -n "$i" ] && echo "dhcp-host=$m,$i"
        done < "$RESERV_FILE"
      } > "$DNSMASQ_RESERV.tmp"
      mv "$DNSMASQ_RESERV.tmp" "$DNSMASQ_RESERV"
      # Saada dnsmasq-ile SIGHUP — reread hosts
      systemctl reload dnsmasq 2>/dev/null || pkill -HUP -x dnsmasq || true
    fi
    ;;
esac

exit 0
